### ISSUE TITLE
Not possible to add config without creating a rollout

### ISSUE THREAD

**Issue by nickycdk** [rigdev/rig#109]
#### Describe the bug

@andersjohnsen @Munklinde96 
It is not possible to create/add a config file without having created a rollout. The API will return an error when doing so.

It seems like it is somehow tied to the capsules "currentRollout", but when creating a new capsule and you start off by wanting to add a config file, you will get an error: **build not found**

The same actually goes for "Resources & Enviroment variables" as well... Same problem on these

#### To Reproduce

1. In the dashboard, Go to capsules', create a capsule
2. Enter the capsule and go to "Config files" -> try adding a file
3. See error

#### Expected behavior

I would expect it should be possible to add a config without needing to create a build/rollout

**Comment by andersjohnsen** [comment]
Fix in the next version of the platform.
