### ISSUE TITLE
Can't delete capsule from using capsuleId

### ISSUE THREAD

**Issue by nickycdk** [rigdev/rig#116]
#### Describe the bug

Spoke to @andersjohnsen on this issue: 
When trying to delete a capsule using the capsuleId, the following errors occours: 

`write exception: write errors: [Cannot perform a delete with a non-empty query on a time-series collection that does not have a metaField]`

#### To Reproduce

Try to delete a capsule from the dashboard

#### Expected behavior

I can delete a capsule from the dashboard

**Comment by andersjohnsen** [comment]
Fixed in platform :+1:
