### ISSUE TITLE
🐛 Capsule not found on capsule create

### ISSUE THREAD

**Issue by Munklinde96** [rigdev/rig#244]
#### Describe the bug

The first rollout halts very quickly due to the following error:

![image](https://github.com/rigdev/rig/assets/44819039/9310ad99-77f3-4814-bafb-746ffce12bb0)

#### To Reproduce

Create a capsule, create a build and deploy it

**Comment by MatiasFrank** [comment]
I can't reproduce it. Do we know if its still a bug?

**Comment by Munklinde96** [comment]
probably not. I will close
