### ISSUE TITLE
Getting started guide has some oddeties.

### ISSUE THREAD

**Issue by Moulde** [rigdev/rig#281]
#### Describe the bug

I'm trying to follow the getting started guide, and getting some weird errors / responses form the cli.
https://docs.rig.dev/getting-started/first-capsule

1. When creating the build, i get a build-id, but the build-id is not recognized when i try to deploy - (also it's not clear if the whole imagename + digest is the image id or if the image name is enough)

```
rig capsule -c nginx-capsule build create --image nginx:latest
Created new build: index.docker.io/library/nginx:latest@sha256:d2e65182b5fd330470eca9b8e23e8a1a0d87cc9b820eb1fb3f034bf8248d37ee

rig capsule -c nginx-capsule deploy --build-id index.docker.io/library/nginx:latest@sha256:d2e65182b5fd330470eca9b8e23e8a1a0d87cc9b820eb1fb3f034bf8248d37ee
Error: no builds matched the image name and digest prefix
```

I checked that it had no trailing spaces, the only way i was able to create the deploy, was interactively in the cli by not specifying the build-id at all.

2. The `rig capsule list-rollouts -c nginx-capsule` command does not seem to work.
It seems like it should instead be -> `rig capsule rollout get -c nginx-capsule`

3. The `rig capsule -c nginx-capsule resource scale --replicas 3` doesnt seem to work.
Should it be `rig capsule scale horizontal -c nginx-capsule --replicas 3`

4. After applying the network config successfully, I was not able to access the nginx default page. Tried a different port, and redid the config and deploy a couple of times, but no dice.

#### Additional contextual information

- OS: MacOS Ventura 13.4.1
- Browser incl. version: Safari Version 16.5.1 (18615.2.9.11.7)
- Rig Version: rig 1.3.0
- Cluster Type and version: Docker 

Client:
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:28:49 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux
```
Server: Docker Desktop 4.24.2 (124339)
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:31:36 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by Munklinde96** [comment]
Hi Moulde, thanks for your feedback, and for bringing this to out attention. I will address your issues in order:
1. There was an error in our CLI. this is fixed with #285
2. Fixed in rigdev/docs/pull/35
3. Fixed in rigdev/docs/pull/35
4. My guess would be that it does not work, since you are on an arm CPU, and thus must use another nginx image - If you use arm64v8/nginx:latest it should work - I will add this as a note in the docs.

Hope this helps
