### ISSUE TITLE
Click "Create your first capsule" -> Click "Get started", nothing happens

### ISSUE THREAD

**Issue by lasseco** [rigdev/rig#34]
**Describe the bug**
Click "Create your first capsule" -> Click "Get started", nothing happens. No "get started" documentation appears.

**To Reproduce**
1. Install Rig on docker.
2. Log in
3. Click "Create your first capsule"
4. Click "Get started"
5. Nothing happens

**Expected behavior**
Redirect to get started guide

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lasseco** [comment]
Same with "Add your first build" -> "Add build", etc.

**Comment by nickycdk** [comment]
@lasseco 
This is fixed. For now, the whole block has been replaced by another where we don't have steps.
