### ISSUE TITLE
Explore docs button on Welcome to Rig page navigates to Create Project Route

### ISSUE THREAD

**Issue by adnan-sheikh** [rigdev/rig#37]
**Describe the bug**
The Explore docs button on the Welcome to Rig page navigates to Create Project Route instead of opening relevant docs link to know how to create a new project in the rig dashboard

**To Reproduce**
1. Go to homepage, '/projects' on the first fresh visit, with Rig welcoming you
2. Click on `Explore docs` button
4. You are navigated to `Create Project` route

**Expected behavior**
Open the link to relevant section in docs related to Creating a new project.

**Desktop:**
 - OS: PopOS (Ubuntu Linux)
 - Browser: Chrome
 - Version: 110.0.5481.177 (Official Build) (64-bit)

**Comment by nickycdk** [comment]
@adnan-sheikh 
This should be fixed in the latest release
