### ISSUE TITLE
Postgres database creation fails with error

### ISSUE THREAD

**Issue by adnan-sheikh** [rigdev/rig#38]
**Describe the bug**
When trying to create a database from dashboard, postgres db fails to be created. MongoDB can be created.
Following error is coming from backend:

```js
{"code":"failed_precondition","message":"cannot register a Postgres database without Postgres being enabled"}
```

**To Reproduce**
1. Create a Project (any name)
2. Go to `Create database` page
3. Select `Postgres` as database type
4. Click on `Continue` and go ahead and type a name and try creating

**Expected behavior**
DB should be created

**Screenshots**
![image](https://github.com/rigdev/rig/assets/40724165/4cf103db-3624-4b61-9bb1-99ac1ee872f5)

**Desktop:**
 - OS: PopOS (Ubuntu Linux)
 - Browser: Chrome
 - Version: Version: 110.0.5481.177 (Official Build) (64-bit)

**Comment by adnan-sheikh** [comment]
Is this because when I copied the docker compose file from getting started docs, it only has mongodb image and no postgres db is there in the docker compose file?

**Comment by Munklinde96** [comment]
Hey @adnan-sheikh, yes that is the case! Note, that we are actively refining the database module, and you can expect the usability to increase very soon.

**Comment by blacksails** [comment]
I think for now we should hide the option to create them until it is fully supported. @nickycdk

**Comment by nickycdk** [comment]
@andersjohnsen @blacksails @adnan-sheikh 
Databases has been removed in the latest release, so it should automatically be solved by this as we no longer show "databases" in the dashboard.
