### ISSUE TITLE
Total capsules counter is a boolean

### ISSUE THREAD

**Issue by lucaryholt** [rigdev/rig#39]
**Describe the bug**
The `Total capsules` counter is displayed as a boolean.

**Expected behavior**
I expect to see a number representing the number of capsules in my project.

**Screenshots**
<img width="397" alt="image" src="https://github.com/rigdev/rig/assets/46486518/040d7661-012e-4b6c-a25d-82e3c6a70d70">

**Desktop (please complete the following information):**
 - OS: MacOS 13
 - Version: 1.0.0

**Comment by blacksails** [comment]
Wow beautiful

**Comment by andersjohnsen** [comment]
Fix in v1.1.0 :)
