### ISSUE TITLE
:bug: go binary install is having package issue

### ISSUE THREAD

**Issue by ankittkp** [rigdev/rig#48]
**Docs Reference**
https://docs.rig.dev/getting-started/cli-setup#from-source

**Describe the bug**
Right now go install is not working, it is giving output
```
go: finding module for package github.com/rigdev/rig/cmd/common
../go/pkg/mod/github.com/rigdev/rig/cmd/rig@v0.0.0-20230906080740-f48eaf0a6f71/cmd/auth/get.go:11:2: module github.com/rigdev/rig@latest found (v1.1.0), but does not contain package github.com/rigdev/rig/cmd/common
```

**To Reproduce**
`go install github.com/rigdev/rig/cmd/rig@main` in fresh installation

**Expected behavior**
This should install the binary gracefully.

**Comment by blacksails** [comment]
Thanks for the report 🙏. We are aware of the issue and working on a fix. Will keep this open for tracking 👍

**Comment by ankittkp** [comment]
> Thanks for the report 🙏. We are aware of the issue and working on a fix. Will keep this open for tracking 👍

I think the fix is simple to upgrade you go dependencies to your latest version, is there any contributions guide let me know. I would like to contribute in this project.

**Comment by blacksails** [comment]
> I think the fix is simple to upgrade you go dependencies to your latest version, is there any contributions guide let me know. I would like to contribute in this project.

@andersjohnsen is working on it.

With regards to contributing, we should introduce a CONTRIBUTING.md. Feel free to create another issue for it :)

**Comment by ankittkp** [comment]
> > I think the fix is simple to upgrade you go dependencies to your latest version, is there any contributions guide let me know. I would like to contribute in this project.
> 
> @andersjohnsen is working on it.
> 
> With regards to contributing, we should introduce a CONTRIBUTING.md. Feel free to create another issue for it :)

Sure, here we go https://github.com/rigdev/rig/issues/48#issuecomment-1707981118

**Comment by blacksails** [comment]
`go install github.com/rigdev/rig/cmd/rig@v1.1.2` works now `go install github.com/rigdev/rig/cmd/rig@main` does not. Lets keep this open until we solve it so that the CLI can be installed from any commit reference.

**Comment by ankittkp** [comment]
> `go install github.com/rigdev/rig/cmd/rig@v1.1.2` works now `go install github.com/rigdev/rig/cmd/rig@main` does not. Lets keep this open until we solve it so that the CLI can be installed from any commit reference.

i guess this is installed, but something still wrong

```
➜ rig rig auth login --email=talktoankitk@gmail.com  
Error: unknown flag: --email
Usage:
  rig auth login [flags]

Flags:
  -h, --help              help for login
  -p, --password string   password of the user
  -u, --user string       useridentifier [username | email | phone number]
```

my version
```
➜  rig rig version -v                               
rig dev
commit: none
date: unknown
```

**Comment by ankittkp** [comment]
> 

cool, that is successful. That means `--email` flag is having bug.

**Comment by andersjohnsen** [comment]
Yes, `email` is deprecated in favor of none (interactive), or `--username <email>`.

**Comment by blacksails** [comment]
```
❯ go install github.com/rigdev/rig/cmd/rig@main
go: downloading github.com/rigdev/rig v1.4.1-0.20231120092906-8f84f3ba00a3
go: finding module for package github.com/rigdev/rig/cmd/common
go: downloading github.com/rigdev/rig v1.4.0
go: found github.com/rigdev/rig/cmd/common in github.com/rigdev/rig v1.4.0
ambiguous import: found package github.com/rigdev/rig/cmd/rig in multiple modules:
        github.com/rigdev/rig v1.4.0 (/Users/blacksails/go/pkg/mod/github.com/rigdev/rig@v1.4.0/cmd/rig)
        github.com/rigdev/rig/cmd/rig v0.0.0-20230906091239-bd04b590bcf0 (/Users/blacksails/go/pkg/mod/github.com/rigdev/rig/cmd/rig@v0.0.0-20230906091239-bd04b590bcf0)
```

**Comment by andersjohnsen** [comment]
Finally identified the issue: https://github.com/golang/go/issues/64279
