### ISSUE TITLE
✨ Expose cluster capabillities in a ConfigMap

### ISSUE THREAD

**Issue by blacksails** [rigdev/rig#480]
When working with multiple clusters we currently need the operator GRPC interface to be exposed from every cluster in order to read the capabilities of each cluster. It would be simpler if we could just use the kubernetes API to get the capabilities of a cluster.

Proposal: Let the operator own a ConfigMap which contains it's capabilities. Then the rig-platform can read this ConfigMap in order to know what capabilities the given cluster has.

**Comment by andersjohnsen** [comment]
We found a different way of exposing the Operator APIs
