### ISSUE TITLE
Loading logs is inconsistent

### ISSUE THREAD

**Issue by Munklinde96** [rigdev/rig#488]
#### Describe the bug

The loaded logs are not always the newest. At times, the dashboard fails to load the newest logs, and instead keeps showing a set of old logs on every refresh. At the same time, new logs do not appear. At other times it works fine.

Restarting the instances fixes this

#### Expected behavior

To always see the newest logs

#### Screenshots
Even though there have been plenty of logs since:

<img width="1420" alt="image" src="https://github.com/rigdev/rig/assets/44819039/1fc31919-5a19-4db2-96ac-67c18905d2a2">

**Comment by andersjohnsen** [comment]
I fixed logs viewing last week, please reopen if it's still an issue :)
