### ISSUE TITLE
Error on creating service account

### ISSUE THREAD

**Issue by flobaader** [rigdev/rig#496]
#### Describe the bug

When creating a service account on the web ui the following error occurs:

`Error creating Service Account!ConnectError: [permission_denied] no project selected`

<img width="1211" alt="image" src="https://github.com/rigdev/rig/assets/16624361/96ff57d4-3930-4fc5-be83-e255db292e6a">

#### To Reproduce

1. Create new project
2. Create new service account

#### Additional contextual information

ghcr.io/rigdev/rig-platform:0.4.4
ghcr.io/rigdev/rig-operator:1.5.5

**Comment by MatiasFrank** [comment]
Thanks for trying out Rig and opening the issue! The bug is fixed on main and we'll make a release in the coming days. I'll close the issue once the new release is out.

**Comment by flobaader** [comment]
works now
