### ISSUE TITLE
Add "Resources" tab to rollouts

### ISSUE THREAD

**Issue by andersjohnsen** [rigdev/rig#564]
Here we can list (like in the Review panel) the resources associated with the rollout, and all of their content.

**Comment by nickycdk** [comment]
Might need an explanation of what you exactly mean and have in mind as I dont feel it is quite descriptive enough? @andersjohnsen @JackRigDev 

What resources to you want to list and where? The review modal primarily shows a diff and what has changed? So I cant see how it has anything related with a rollout as such.

**Comment by nickycdk** [comment]
CC @andersjohnsen

**Comment by JackRigDev** [comment]
[Design ](https://www.figma.com/file/SURnpwjLAsew7wwklZdj9F/Capsules?type=design&node-id=2762%3A9323&mode=design&t=fVvfIsUUW1wHWKyb-1)

**Comment by nickycdk** [comment]
@andersjohnsen This is now done, moving it to testing as I would like your eyes on it, just to make sure everything is as it should be. Moving it to "In test"

**Comment by nickycdk** [comment]
@andersjohnsen approved it, so merging now. Out with next release
