### ISSUE TITLE
Various Cron Job bugs

### ISSUE THREAD

**Issue by MatiasFrank** [rigdev/rig#570]
- [x] The cron schedule cannot be empty, but is allowed to be it. This results in an error when you deploy the Cron job 
- [x] The cron schedule `* * * * *` is displayed as `triggers constantly`. It should be `Triggers every minute` instead.
- [x] Deleting the last cron job doesn't remove it from the list until you refresh the page
- [x] Deleting a cron job should be a queued change as well
- [x] Ordering of job execution should be newest execution first

**Comment by nickycdk** [comment]
@MatiasFrank - This is now fixed, will be out in next release
