### ISSUE TITLE
Duplicated std:out on user input

### ISSUE THREAD

**Issue by Razkaroth** [rigdev/rig#58]
**Describe the bug**
Standard output seems to be duplicated whenever the user inputs something.

**To Reproduce**
1. run something like `rig config init`
2. Follow the instructions.

**Expected behavior**
It should not send duplicated messages to standard output.

**Screenshots**
![image](https://github.com/rigdev/rig/assets/32623705/61180172-d23c-4df6-befe-edc14547779b)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 22H2 Build 22621.2215

**Comment by MatiasFrank** [comment]
There are some bugs in our CLI prompting library (https://github.com/manifoldco/promptui). The library does not seem to be maintained anymore so we'll have to find a replacement

**Comment by MatiasFrank** [comment]
I've changed our prompting library to [promptkit](https://github.com/erikgeiser/promptkit) and so far haven't seen issues with duplicated lines
