### ISSUE TITLE
Abort-button in the dashboard does not seem to work

### ISSUE THREAD

**Issue by MatiasFrank** [rigdev/rig#589]
Clicking the abort-button on a current rollout does not make an abort-request.

Also, clicking `Abort` in the dropdown menu on the Rollout list page does send a request, but not with environment ID set.
<img width="358" alt="Screenshot 2024-02-06 at 14 22 19" src="https://github.com/rigdev/rig/assets/24476600/b2c29cf9-561c-49ce-a0e1-0f1b570d02da">

**Comment by MatiasFrank** [comment]
Ahh right yea, that's a backend issue

**Comment by Munklinde96** [comment]
added it in #600, so you can add it now @nickycdk, it we are good

**Comment by nickycdk** [comment]
Fixed in : https://github.com/rigdev/dashboard/commit/82bc3594081e38a56282f7dc958dcc10686111da - Will go into next release
