### ISSUE TITLE
Network interfaces on dashboard is buggy.

### ISSUE THREAD

**Issue by Munklinde96** [rigdev/rig#596]
Adding a new interface will sometimes delete the current one.

I had an existing network interface, and upon adding a new one, it deleted the already existing one.

**Comment by nickycdk** [comment]
@Munklinde96 - Should be fixed in: https://github.com/rigdev/dashboard/commit/0bb4a21666b419a6dcd82a6ca9e0b6aeeceb32ec 

Will go into next release
