### ISSUE TITLE
Remove the option of deleting a build that is in use

### ISSUE THREAD

**Issue by Munklinde96** [rigdev/rig#597]
Remove the option of deleting a build that is in use - Across environments! I guess this goes for both backend and frontend

**Comment by Munklinde96** [comment]
Fixed in backend in rigdev/platform#306

**Comment by nickycdk** [comment]
Fixed in FE as well in: https://github.com/rigdev/dashboard/commit/2a9bbac62f2682efbddf6173b35b891a1b00e11a

**Comment by nickycdk** [comment]
Will go into next release
