### ISSUE TITLE
Add Capsule and Project change Dropdown.

### ISSUE THREAD

**Issue by andersjohnsen** [rigdev/rig#603]
[Figma File](https://www.figma.com/file/fPvupL9fOsIFIDzg8lBtdG/Projects?type=design&node-id=1693%3A30993&mode=design&t=3p5sTYpJpPnTVbKu-1)

Implementation of the 'Change Capsules or Project' dropdowns within the navigation.
Also the removal of the 'Projects' breadcrumb (see designs).

**Comment by nickycdk** [comment]
This is now implemented (in https://github.com/rigdev/dashboard/commit/c8c767197dc8a289463cc90c236c542a7edbf052) and will go into the next release...
