### ISSUE TITLE
Request to Update Twitter Icon to X

### ISSUE THREAD

**Issue by lalitkumawat1m** [rigdev/rig#64]
**Describe the bug**

Twitter logo is updated recently and hasnt been updated on the site. I didnt find any issue related to this.

**To Reproduce**
1. Go to Footer section and see Twitter old logo

**Screenshots**
<img width="960" alt="Screenshot 2023-09-07 155604" src="https://github.com/rigdev/rig/assets/91591901/54e224ab-dd99-4640-a5a4-9b91964a8195">

**Additional context**
Won't change anything in the code as such would replace the twitter-logo.png with a new file. No code will be touched.

@blacksails 
I want to work on this issue please assign this to me.

**Comment by nickycdk** [comment]
@lalitkumawat1m .
Thanks for noticing. This is however on the website, and not in this project as such.
However, this should now be corrected on the website. Thanks for the heads up.
