### ISSUE TITLE
cli auth login --email flag is not working

### ISSUE THREAD

**Issue by ankittkp** [rigdev/rig#66]
**Describe the bug**
rig auth login --email flag is not working 
```
➜  rig rig auth login
User Identifier (username, email or phone number): talktoankitk@gmail.com
Enter Password ************█
Login successful!
➜  rig rig version   
rig dev
➜  rig rig auth login --email=talktoankitk@gmail.com
Error: unknown flag: --email
Usage:
  rig auth login [flags]

Flags:
  -h, --help              help for login
  -p, --password string   password of the user
  -u, --user string       useridentifier [username | email | phone number]

```

**Expected behavior**
rig auth login is working fine but with flag is not.

**Comment by Dean-Coakley** [comment]
@ankittkp I have not used this cli but I think I understand it from the output and reading some of the code.

I believe the expected usage for your example would be:
```shell
➜  rig rig auth login --user=talktoankitk@gmail.com
```

The arg is `--user` and it expects you to pass `useridentifier` as the value which can be a `username`, or an `email`, or a `phone number`.


> Note you may also have to pass a password for the command to work:
```shell
➜  rig rig auth login --user=talktoankitk@gmail.com --password=************
```

**Comment by Munklinde96** [comment]
Yes correct @Dean-Coakley, thank you both for making us aware. I have changed this in the documentation and will close the issue now.
