### ISSUE TITLE
:bug: IPV6 support on kubernetes installation

### ISSUE THREAD

**Issue by isaccavalcante** [rigdev/rig#69]
When deploying rig thought the helm chart in an IPV6 Kubernetes cluster, mongo pod wont start because it binds to the default IPV4 address. Would be good to have a way to pass extra args to the mongodb container, so we could enable IPV6 binding with:

```
  args:
  - "--ipv6"
  - "--bind_ip_all"
```

Ref: https://www.mongodb.com/docs/manual/core/security-mongodb-configuration/#ip-binding

**Comment by andersjohnsen** [comment]
Fixed in next release. Note that we've added postgres support as well.
