### ISSUE TITLE
CLI improvements for better CI/CD

### ISSUE THREAD

**Issue by blacksails** [rigdev/rig#705]
The CLI needs to be improved to give a nice experience in CI

- [x] #709
- [x] #723
- [x] Improve configuration
  - [x] #707
  - [x] #706
- [x] #708
- [x] #710
- [x] #711

**Comment by andersjohnsen** [comment]
When non-interactive (no terminal on stdin), we expect a RIG_CLIENT_ID and RIG_CLIENT_SECRET to be present, if no config file exists.

**Comment by blacksails** [comment]
> When non-interactive (no terminal on stdin), we expect a RIG_CLIENT_ID and RIG_CLIENT_SECRET to be present, if no config file exists.

I would rather say we expect credentials to be configured in the rig config file, but we let flags/env vars be ways of overriding their values.

When loading the config
1. Load the config file
2. Override from flags
3. Override from envvars

Which then makes for the full config.

**Comment by andersjohnsen** [comment]
That's in effect what's happening - but this way we allow running without a config file.
