### ISSUE TITLE
Ensure that every prompt is based on a flag or argument

### ISSUE THREAD

**Issue by blacksails** [rigdev/rig#708]
In order to enable all commands to be scripted or run in CI, we need to support that they are run in a non-interactive manner.

Most importantly:
- `rig config` it should be easy to manipulate the configuration.
- `rig capsule deploy` it should be easy to deploy images.
- `rig capsule image create` it should be easy to add images to capsules.

**Comment by andersjohnsen** [comment]
All base args are now backed by a flag as well.
