### ISSUE TITLE
Use XDG_CONFIG_HOME for storing CLI config on macos

### ISSUE THREAD

**Issue by blacksails** [rigdev/rig#712]
Currently CLI config is stored under `~/Library/Application\ Support/rig/config.yaml` it would be easier to quickly take a look at the configuration if we used the `XDG_CONFIG_HOME` standard which most other CLIs support. We could also consider having an environment variable for setting where to look for the configuration like `kubectl` has `KUBECONFIG`.

Using `XDG_CONFIG_HOME`, the configfile location would be `~/.config/rig/config.yaml`.

**Comment by andersjohnsen** [comment]
There seams to be an exception made for CLI tools, to follow the usual unix way of using `~/.config/` pattern. :heavy_plus_sign:1 on doing the change now.
