### ISSUE TITLE
Use helm trick to roll deployment on config changes

### ISSUE THREAD

**Issue by blacksails** [rigdev/rig#97]
#### Describe the bug

If the rig config is changed and the helm chart updates the configuration, the deployment isen't restarted

#### To Reproduce

1. Install helm chart.
2. Change configuration and update the helm release

#### Expected behavior

Deployment is restarted with the new config

#### Solution

Set the shasum of the config as an annotation on the pod in the pod template: https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments

**Comment by blacksails** [comment]
When this is fixed we can also remove this line https://github.com/rigdev/rig/blob/main/Makefile#L146

**Comment by s1ntaxe770r** [comment]
hey @blacksails any chance i could take this? 

if I'm not mistaken, looks like just need to set the correct annotation over [here ](https://github.com/rigdev/rig/blob/40dc3399e5c30a43f91100ab94a00fd3a6d6d969/deploy/charts/rig/values.yaml#L35) ?

**Comment by blacksails** [comment]
Sure go ahead. You wont be able to set it through values though, as you cannot calculate a shasum in the valuefile. You will need to change the podtemplate metadata template here: https://github.com/rigdev/rig/blob/40dc3399e5c30a43f91100ab94a00fd3a6d6d969/deploy/charts/rig/templates/deployment.yaml#L13C6-L13C6

**Comment by s1ntaxe770r** [comment]
@blacksails  apologies for the delay didn't get a notification in time 😅
